return {
    ['Sword'] = {
        ['Wooden Sword'] = {Damage = 1, Speed = 1, Rarity = 'TBD', Thumbnail = 'TBD'},
        ['Superior Wooden Sword'] = {Damage = 2, Speed = 3, Rarity = 'TBD', Thumbnail = 'TBD'},
        ['Iron Sword'] = {Damage = 3, Speed = 1, Rarity = 'TBD', Thumbnail = 'TBD'},
        ['Superior Iron Sword'] = {Damage = 4, Speed = 300, Rarity = 'TBD', Thumbnail = 'TBD'}
    },
    ['Spacing'] = 5,
    ['MaxClimbHeight'] = 6
}