return {
    Coins = 0,
    Weapons = {
        ['Default'] = {
        weaponName = 'Wooden Sword',
        weaponType = 'Sword',
        equipped = true
        },

        ['Default1'] = {
            weaponName = 'Wooden Sword',
            weaponType = 'Sword',
            equipped = true
        },

        ['Default2'] = {
            weaponName = 'Wooden Sword',
            weaponType = 'Sword',
            equipped = true
        },

        ['Default3'] = {
            weaponName = 'Wooden Sword',
            weaponType = 'Sword',
            equipped = true
        },
    },
    MaxWeaponsEquipped = 4,
    WeaponStorageMax = 50,
    ZonesUnlocked = {}
}