return {
    Coins = 0,
    Weapons = {
        ['Default'] = {
        weaponName = 'Wooden Sword',
        weaponType = 'Sword',
        equipped = true
        },
        ['Default2'] = {
            weaponName = 'Wooden Sword',
            weaponType = 'Sword',
            equipped = true
        },
        ['Default3'] = {
            weaponName = 'Wooden Sword',
            weaponType = 'Sword',
            equipped = true
        },
        ['Default4'] = {
            weaponName = 'Wooden Sword',
            weaponType = 'Sword',
            equipped = true
        },
        ['Default5'] = {
            weaponName = 'Wooden Sword',
            weaponType = 'Sword',
            equipped = true
        },
        ['Default6'] = {
            weaponName = 'Wooden Sword',
            weaponType = 'Sword',
            equipped = true
        }
    },
    MaxWeaponsEquipped = 4,
    WeaponStorageMax = 50,
    ZonesUnlocked = {}
}